runtime: go
api_version: go1.8

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

skip_files:
- ^node_modules/.+$
- ^src/.+$
- ^public/.+$
